server.port=8080
spring.data.mongodb.uri=mongodb://localhost:27017/portfolio-tracker
spring.data.mongodb.database=portfolio-tracker

# Enable CORS globally
endpoints.cors.allowed-origins=http://localhost:4200
endpoints.cors.allowed-methods=GET,POST,PUT,DELETE